### PR TITLE
First pull

### PR DESCRIPTION
**Pull request by cramirezs**
I'm checking I can work on the files from R and make it easier.

### CODE REVIEW

**Comment by annakrystalli** [comment]
Ciro this is great! I'm so glad you went through the tutorial! Does that mean you've got all the code set up in an RStudio project?! 🎉 If so you should be able to just run: **Shapefile_processing_reptiles_demo.R** after a simple amendment: **delete (if using a Rstudio project) or update (to folder with all scripts) line 13 (`setwd("~/Documents/workflows/Sex Roles in Birds/birds/")`)**

I'm not going to accept the merge, just because this repo (mine, the one you are trying to send changes to) is primarily for the birds project I have been working on so want to keep it clean with only my own files. However, I'm glad you went through the whole process! Now you know what to do when you want to contribute to someone else's project! 😃 Fork, make changes, create pull request!

**Comment by annakrystalli** [comment]
In case that doesn't make sense. The tutorial was made to contribute to a repo designed for a workshop.

**Comment by cramirezs** [comment]
Hi, Anna

Yes, I read the tutorial. But it was easy because I've done it before, so I
jus had to remember (a big part though).

Sorry for the pull request. I was testing it and also I didn't understood
it well. But thanks for make that part clear. Hope your project's going
fine.

I'm running the code right now. And I hope we can keep in touch in case I
need a hand.

Saludos,
Ciro

P.S. I think I found you on Facebook, so I added you. Glad if you either
reject or accept the friend request.

Ciro

**Comment by annakrystalli** [comment]
No worries at all re pull request. And yes let me know if you get stuck. Good luck!

**Pull request closed without merging**
